//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangXH
    {
        public string TenTK { get; set; }
        public string TenNV { get; set; }
        public Nullable<double> Diem { get; set; }
        public Nullable<int> ThuHang { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
